services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.api.routes
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A src.core.queue.celery_config worker -l INFO
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: